version: '3.8'

services:
  # FastAPI application
  app:
    build: .
    container_name: smartwatch-monitoring-app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./app/templates/reports:/app/app/templates/reports
      - ./app.log:/app/app.log
      - ./server.log:/app/server.log
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-ml_monitoring}
      - POSTGRES_PORT=5432
      - USE_SQLITE=${USE_SQLITE:-false}
      - PREFECT_API_URL=http://prefect:4200/api
    networks:
      - monitoring-network
    depends_on:
      - postgres
    restart: unless-stopped

  # PostgreSQL database
  postgres:
    image: postgres:14-alpine
    container_name: smartwatch-monitoring-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-ml_monitoring}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - monitoring-network
    restart: unless-stopped

  # Prefect server
  prefect:
    image: prefecthq/prefect:2-latest
    container_name: smartwatch-monitoring-prefect
    ports:
      - "4200:4200"
    command: prefect server start --host 0.0.0.0
    volumes:
      - prefect-data:/root/.prefect
    networks:
      - monitoring-network
    restart: unless-stopped

  # Simulate smartwatch clients
  simulator:
    build: .
    container_name: smartwatch-client-simulator
    command: python scripts/simulate_smartwatch_clients.py --interval 5
    volumes:
      - ./data:/app/data
    networks:
      - monitoring-network
    depends_on:
      - app
    restart: unless-stopped

networks:
  monitoring-network:
    driver: bridge

volumes:
  postgres-data:
  prefect-data: